### ISSUE TITLE
Is it hosted somewhere ?

### ISSUE THREAD

**Issue by redouane59** [antbrl/citadels-server#1]
Hey,

Did you host your project somewhere to test it as a client?

**Comment by antbrl** [comment]
Hi, you may find a demo instance hosted on https://citadelles.herokuapp.com. This may be buggy with 4+ players in the same room though. I'll have to fix that someday.

**Comment by redouane59** [comment]
It supports french, it's awesome !!
What do you mean by buggy ? 3 players is working perfectly well but with 4 to 7 it crashes ?

**Comment by antbrl** [comment]
Thanks! I mean that I have thoroughly tested 2 and 3 players, but last time I played with 4 players some turns or actions were skipped.

**Comment by redouane59** [comment]
If I have the opportunity to test it with 4 or more players, could it be interesting for you that I created issues ? Or don't you have time to fix it ? If I can help on any way doing tests I would be happy to do so.

**Comment by antbrl** [comment]
Please do! I will definitely find some time to fix the bugs if I can reproduce them more easily.
