### ISSUE TITLE
L'assassin is not working against Magicien or Eveque

### ISSUE THREAD

**Issue by redouane59** [antbrl/citadels-server#2]
The "Magicien" was killed by  the "Assassin" at the beginning of the turn but then the Magicien can play normally when it's his turn

Here is a video showing that it is not selected well  : https://watch.screencastify.com/v/KJesTTJt2wWYJts0ifY5

Here is a screenshot of the turn of the Magicien : 
![image](https://user-images.githubusercontent.com/4500524/181903317-4b8a4623-9f10-4651-b4dd-90e9d2364cea.png)

**Comment by redouane59** [comment]
I just made another test when the Assassin killed the Voleur and it works well as expected

**Comment by redouane59** [comment]
On this example, I selected the "Eveque" to be killed but it seems like it was not taken into account even if the action is not available anymore.
![image](https://user-images.githubusercontent.com/4500524/181903671-c34c526e-f934-4326-bc4e-1cc78c6ef2a9.png)

Eveque turn : 
![image](https://user-images.githubusercontent.com/4500524/181903721-1169cae2-dacc-463c-bc85-40c062e2a40b.png)

**Comment by antbrl** [comment]
Fixed by commit aca08011a2b1330cc0ae6d7596238075a5bc4717.
