### ISSUE TITLE
King selected when Eveque is chosen by Assassin / Voleur

### ISSUE THREAD

**Issue by redouane59** [antbrl/citadels-server#3]
See the video below : 
https://watch.screencastify.com/v/QwAfbjb4IK9DjqC16CMo

I selected the Eveque and the Roi was killed.

**Comment by redouane59** [comment]
Same case with the Voleur.
I wanted to take the money of the Eveque and it selected the Roi without any reason.
![image](https://user-images.githubusercontent.com/4500524/181904295-7e5613a3-4b27-4eae-bec7-fd7a2f33dd9f.png)

**Comment by antbrl** [comment]
Fixed by commit aca08011a2b1330cc0ae6d7596238075a5bc4717.

**Comment by redouane59** [comment]
Great, thanks for the quick fix ! 
I'm going to try to test it again tomorrow and I'll keep you informed :)
